# Generated by Django 5.1.5 on 2025-02-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('exploitable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('exploitable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('port_no', models.PositiveIntegerField()),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('exploitable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('endpoint_name', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('edges', models.ManyToManyField(blank=True, to='core.endpoint')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='core.port')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='core.workspace'),
        ),
    ]
