# Generated by Django 5.1.5 on 2025-02-07 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='edges',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='edges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.endpoint'),
        ),
    ]
