# Generated by Django 5.1.5 on 2025-02-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_endpoint_edges_endpoint_edges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
