# Generated by Django 5.1.5 on 2025-03-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_host_ipv4_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='edges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='core.endpoint'),
        ),
    ]
