# Generated by Django 5.1.5 on 2025-03-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_endpoint_edges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endpoint',
            old_name='edges',
            new_name='parent',
        ),
    ]
